### ISSUE TITLE
Link from the readme 404s

### ISSUE THREAD

**Issue by mayeaux** [use-cookie-consent/use-cookie-consent-core#14]
From readme: you should use this (not yet done) package

The link it points to 404s

https://github.com/use-cookie-consent/use-cookie-consent-core/blob/main

**Comment by bring-shrubbery** [comment]
@mayeaux  Yeah, I wrote that couple of days ago when the repo was not there yet. I updated it now, but that repo is still not functional, I'll update it this weekend to have everything needed. For now, you can just use this core package, the only difference is described in #4 which is just that it won't reactively update between components.
